<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>Tratamento de erros em JS</title>
</head>
<body>
	<p id="demo"></p>
	<input type="text" id="demo2" max="5">
	<button type="button" onclick="myFunction()">Entrada de teste</button>
	<p id="p01"></p>
	<p id="demo3"></p>
	<p id="demo4"></p>
	<p id="demo5"></p>
	<p id="demo6"></p>
	<p id="demo7"></p>

	<script>
		/*The try statement lets you test a block of code for errors.
		The catch statement lets you handle the error.
		The throw statement lets you create custom errors.
		The finally statement lets you execute code, after try and catch, regardless of the result.*/

		/*When executing JavaScript code, different errors can occur. Errors can be coding errors made by the programmer, errors due to wrong input, and other unforeseeable things.*/
		try{
			adddlert("Bem vindo!");
		}
		catch(err){
			document.getElementById("demo").innerHTML = err.message;
		}
		//JavaScript catches adddlert as an error, and executes the catch code to handle it.

		/*The try statement allows you to define a block of code to be tested for errors while it is being executed.
		The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.
		The JavaScript statements try and catch come in pairs*/

		/*When an error occurs, JavaScript will normally stop and generate an error message.
		The technical term for this is: JavaScript will throw an exception (throw an error).
		JavaScript will actually create an Error object with two properties: name and message.*/

		/*The throw statement allows you to create a custom error.
		Technically you can throw an exception (throw an error).
		The exception can be a JavaScript String, a Number, a Boolean or an Object:
		throw "Too big";    // throw a text
		throw 500;          // throw a number
		If you use throw together with try and catch, you can control program flow and generate custom error messages.
		*/

		/*This example examines input. If the value is wrong, an exception (err) is thrown.
		The exception (err) is caught by the catch statement and a custom error message is displayed*/
		function myFunction(){
			var message, x;
			message = document.getElementById("p01");
			message.innerHTML = "";
			x = document.getElementById("demo2").value;
			try{
				if(x == "") throw "empty";
				if(isNaN(x)) throw "not a number";
				x = Number(x);
				if(x < 5) throw "too low";
				if(x > 10) throw "too high";
			}
			catch(err){
				message.innerHTML = "Input is " + err;
			}
			/*The finally statement lets you execute code, after try and catch, regardless of the result.*/
			finally{
				document.getElementById("demo").value = "";
			}
		}

		/*
		The code above is just an example.
		Modern browsers will often use a combination of JavaScript and built-in HTML validation, using predefined validation rules defined in HTML attributes.
		<input id="demo" type="number" min="5" max="10" step="1">
		*/

		/*An EvalError indicates an error in the eval() function.
		Newer versions of JavaScript do not throw EvalError. Use SyntaxError instead.*/

		/*A RangeError is thrown if you use a number that is outside the range of legal values.
		For example: You cannot set the number of significant digits of a number to 500.*/
		var num = 1;
		try{
			num.toPrecision(500);
		}
		catch(err){
			document.getElementById("demo3").innerHTML = err.name;
		}

		/*A ReferenceError is thrown if you use (reference) a variable that has not been declared.*/
		var x;
		try{
			x = y + 1;
		}
		catch(err){
			document.getElementById("demo4").innerHTML = err.name;
		}

		/*A SyntaxError is thrown if you try to evaluate code with a syntax error.*/
		try{
			eval("alert('Hello)");
		}
		catch(err){
			document.getElementById("demo5").innerHTML = err.name;
		}

		/*A TypeError is thrown if you use a value that is outside the range of expected types.*/
		var num = 1;
		try{
			num.toUpperCase();
		}
		catch(err){
			document.getElementById("demo6").innerHTML = err.name;
		}

		/*A URIError is thrown if you use illegal characters in a URI function.*/
		try{
			decodeURI("%%%");
		}
		catch(err){
			document.getElementById("demo7").innerHTML = err.name;
		}
		/*Mozilla and Microsoft defines some non-standard error object properties:
		fileName (Mozilla)
		lineNumber (Mozilla)
		columnNumber (Mozilla)
		stack (Mozilla)
		description (Microsoft)
		number (Microsoft)
		Do not use these properties in public web sites. They will not work in all browsers.*/
	</script>
</body>
</html>